/**
 * Canonical FlowQ job types.
 *
 * This file is the single source of truth for what a "job" is across the
 * entire system. The API, the worker, and any external producer that
 * imports @flowq/sdk all agree on these shapes. If a field changes here,
 * it changes everywhere — that is intentional.
 *
 * Timestamps are stored as Unix epoch milliseconds (number) on the wire
 * and inside Redis. PostgreSQL stores them as TIMESTAMPTZ for
 * queryability; the conversion happens in the persistence layer, not
 * here.
 */

/**
 * The lifecycle states a job moves through.
 *
 *   PENDING   ──► ACTIVE ──► COMPLETED
 *                    │
 *                    └────► FAILED ──► (retry) ──► PENDING
 *                                  │
 *                                  └─(attempts > maxAttempts)─► DEAD
 *
 * String-valued enum (not numeric) so values are stable across processes,
 * grep-friendly, and serialize cleanly to JSON, Redis, and Postgres.
 */
export enum JobStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  DEAD = 'DEAD',
}

/**
 * A FlowQ job — every field, fully specified, no optionals-by-omission.
 *
 * Nullable fields use `| null` rather than `?:` so consumers must
 * actively decide what to do when the value is absent. This forces
 * better error handling at every callsite.
 */
export interface Job {
  /** UUID v4 generated by the API at enqueue time. */
  id: string;

  /** Logical queue this job belongs to (e.g. "emails", "reports"). */
  queueName: string;

  /** Producer-supplied JSON payload. Opaque to FlowQ. */
  payload: Record<string, unknown>;

  /** 1-10, higher = more urgent. Used to bias scheduling within a queue. */
  priority: number;

  /** Current lifecycle state. */
  status: JobStatus;

  /** Number of times we have attempted to execute this job. */
  attempts: number;

  /** Maximum allowed attempts before the job is moved to DEAD. */
  maxAttempts: number;

  /** Seconds to delay first execution after enqueue. */
  delay: number;

  /**
   * Producer-supplied dedup key. If present and a non-DEAD job already
   * exists with the same key, the enqueue is a no-op.
   */
  idempotencyKey: string | null;

  /** Unix epoch ms — when the job was created. */
  createdAt: number;

  /**
   * Unix epoch ms — when the job becomes eligible for execution.
   * Equal to `createdAt + delay*1000` for delayed jobs, otherwise
   * equal to `createdAt`. This is the ZSET score in Redis.
   */
  scheduledAt: number;

  /** Unix epoch ms — when a worker most recently claimed the job. */
  startedAt: number | null;

  /** Unix epoch ms — when the job reached COMPLETED. */
  completedAt: number | null;

  /** Unix epoch ms — when the job most recently transitioned to FAILED. */
  failedAt: number | null;

  /** Stringified error from the most recent failed attempt. */
  lastError: string | null;

  /** ID of the worker currently (or most recently) processing this job. */
  workerId: string | null;

  /**
   * Maximum seconds a worker may hold the job before it is reclaimed
   * by the scheduler as "stalled". Bounds blast radius from a hung worker.
   */
  timeout: number;
}

/** Default values applied when the producer omits an optional field. */
export const JOB_DEFAULTS = {
  priority: 5,
  maxAttempts: 3,
  delay: 0,
  timeout: 30,
} as const;

/** TTL applied to the idempotency lookup key in Redis. */
export const IDEMPOTENCY_TTL_SECONDS = 24 * 60 * 60;

// ---------------------------------------------------------------------------
// Producer-facing input shape
// ---------------------------------------------------------------------------

/**
 * Arguments accepted by `FlowQClient.enqueue`.
 *
 * Optional fields fall back to {@link JOB_DEFAULTS} server-side, so the
 * SDK doesn't apply its own defaults — keeping a single source of
 * truth on the API. The generic `T` lets producers retain payload
 * type-safety end-to-end:
 *
 *   client.enqueue<{ to: string }>({ payload: { to: 'a@b.com' } })
 */
export interface EnqueueInput<T extends Record<string, unknown> = Record<string, unknown>> {
  /** Logical queue name. Required; no implicit "default" queue. */
  queueName: string;
  /** Arbitrary JSON payload handed to the worker. */
  payload: T;
  /** 1–10, higher = more urgent. Default: 5. */
  priority?: number;
  /** Seconds to defer first execution. Default: 0. */
  delay?: number;
  /** Maximum allowed attempts before the job is moved to DEAD. Default: 3. */
  maxAttempts?: number;
  /**
   * Producer-supplied dedup key. If a non-DEAD job already exists with
   * the same key, the API returns the existing job instead of enqueuing
   * a duplicate. Pass `null` to explicitly opt out.
   */
  idempotencyKey?: string | null;
  /** Per-job watchdog timeout in seconds. Default: 30. */
  timeout?: number;
}

// ---------------------------------------------------------------------------
// Read-side response shapes
// ---------------------------------------------------------------------------

/**
 * Returned by `GET /queues/:name/stats`.
 *
 * `enqueued/completed/failed/dead` are durable counters; they only
 * grow. `currentPending/currentActive` are point-in-time depths and
 * may go down. Two distinct categories — keep them mentally separate.
 */
export interface QueueStats {
  queueName: string;
  enqueued: number;
  completed: number;
  failed: number;
  dead: number;
  currentPending: number;
  currentActive: number;
  paused: boolean;
}

/**
 * Worker registry entry returned by `GET /workers`.
 *
 * `status: 'unknown'` is real and intentional — it means the worker id
 * is in the registry SET but its hash has been DEL'd (or vice versa).
 * The dashboard surfaces these as ghosts so the operator notices.
 */
export interface WorkerInfo {
  id: string;
  queue: string | null;
  status: 'idle' | 'busy' | 'unknown';
  startedAt: number | null;
  lastHeartbeat: number | null;
  currentJobId: string | null;
  /** Seconds since lastHeartbeat. `null` if the worker has never beat. */
  staleSeconds: number | null;
}

/** A single row in the dead-letter-queue table. */
export interface DeadLetterRow {
  /** DLQ row primary key (uuid). Distinct from `jobId`. */
  id: string;
  /** Original job id at the time of death. */
  jobId: string;
  queueName: string;
  payload: Record<string, unknown>;
  lastError: string | null;
  attempts: number;
  manuallyRetried: boolean;
  diedAt: number | null;
  retriedAt: number | null;
}

/** Paginated response from `GET /queues/:name/dlq`. */
export interface DLQResponse {
  jobs: DeadLetterRow[];
  total: number;
  page: number;
  limit: number;
}

/** Response from `POST /queues/:name/dlq/:jobId/retry`. */
export interface DLQRetryResponse {
  message: string;
  newJobId: string;
  originalJobId: string;
}

/** Health probe result for an individual dependency. */
export type DependencyStatus = 'ok' | 'error' | 'timeout';

/**
 * Response from `GET /health`.
 *
 * The API returns 200 when `status === 'ok'` and 503 otherwise, so an
 * SDK caller that only cares about "is FlowQ up?" can `await
 * client.health()` and treat any thrown `FlowQServerError` as "down".
 * Inspecting `redis` / `postgres` separately is for richer monitoring.
 */
export interface HealthResponse {
  status: 'ok' | 'degraded';
  redis: DependencyStatus;
  postgres: DependencyStatus;
  /** Seconds since process start. */
  uptime: number;
  /** ISO 8601 timestamp at the moment the probe completed. */
  timestamp: string;
}
