apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flowq.configMapName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "flowq.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ include "flowq.redisHost" . | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  POSTGRES_HOST: {{ include "flowq.postgresHost" . | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | quote }}
  POSTGRES_DB:   {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  API_PORT:      {{ .Values.api.service.port | quote }}
  NODE_ENV:      "production"
  HEARTBEAT_MS:  "15000"
  POLL_INTERVAL_MS: "1000"
