{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flowq.secretName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "flowq.labels" . | nindent 4 }}
type: Opaque
# We use stringData so values aren't double-encoded — Helm/k8s base64s
# them on the way in. Keep these out of git in production; pull from GSM.
stringData:
  POSTGRES_PASSWORD: {{ required "secrets.postgresPassword is required when secrets.create=true" .Values.secrets.postgresPassword | quote }}
  API_KEY:           {{ required "secrets.apiKey is required when secrets.create=true" .Values.secrets.apiKey | quote }}
{{- end }}
